name: 'CI'

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-test-dev-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-test-dev-${{ env.cache-name }}-
      - run: npm ci
      - run: npm run lint
      # TODO: activate once this issue is solved:
      # https://github.com/graphprotocol/graph-ts/issues/113
      # - run: npm run type-check
      - run: npm run codegen
      - run: npm run build

  test_integration:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-test-integration-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-test-integration-${{ env.cache-name }}-

      - uses: actions/checkout@v2
        name: Checkout Barge
        with:
          repository: 'oceanprotocol/barge'
          path: 'barge'
      - name: Run Barge
        working-directory: ${{ github.workspace }}/barge
        env:
          ADDRESS_FILE: ${HOME}/.ocean/ocean-contracts/artifacts/address.json
        run: |
          bash -x start_ocean.sh --with-thegraph --no-dashboard 2>&1 > start_ocean.log &
          for i in $(seq 1 1500); do
            sleep 5
            [ -f "$HOME/.ocean/ocean-contracts/artifacts/ready" ] && break
            done
          cat "$HOME/.ocean/ocean-contracts/artifacts/address.json"
      - run: npm run bargesetup
        env:
          ADDRESS_FILE: /home/runner/.ocean/ocean-contracts/artifacts/address.json
      - run: npm ci
      - name: create and deploy subgraph
        run: |
          npm run codegen
          npm run build
          npm run create:local-barge
          npm run deploy:local-barge
          sleep 20
        env:
          ADDRESS_FILE: /home/runner/.ocean/ocean-contracts/artifacts/address.json
      - run: npm run test-integration
        env:
          ADDRESS_FILE: /home/runner/.ocean/ocean-contracts/artifacts/address.json
