name: "[PROD] - Build and deploy BDP Subgraph"

on:
  push:
    #tags:
    #  - 'prod-v*'
    branches:
      - devops/add_pipeline 

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      INDEXNODE_ENDPOINT: "index.bigdataprotocolmarket.com"
      IPFS_ENDPOINT: "ipfs.bigdataprotocolmarket.com"
      SUBGRAPH_NAME: "oceanprotocol/ocean-subgraph"
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
              node-version: '12'

        - name: Install graph-cli
          run: yarn global add @graphprotocol/graph-cli

        - name: Install dependencies
          run: yarn install

        - name: Codegen
          run: yarn codegen

        - name: Build
          run: yarn build

        - name: Graph create
          run: |
               graph create ${{ env.SUBGRAPH_NAME }} \
                            --version-label $GITHUB_REF_NAME \
                            --node "https://${{ env.INDEXNODE_ENDPOINT }}" \
                            --ipfs "https://${{ env.IPFS_ENDPOINT }}"
                            
        - name: Graph deploy
          run: |
               graph deploy ${{ env.SUBGRAPH_NAME }} \
                            --version-label $GITHUB_REF_NAME \
                            --node "https://${{ env.INDEXNODE_ENDPOINT }}" \
                            --ipfs "https://${{ env.IPFS_ENDPOINT }}"
